---
- hosts: localhost
  become: false

  vars_files:
    - files/packages.yaml
    - files/mounts.yaml
    - files/dconf.yaml
    - files/vim.yaml

  pre_tasks:
    - name: Update Repositories
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'
      apt: update_cache=yes
      changed_when: False

  roles:
    - ansible-role-jet-brains-toolbox

  tasks:
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
      tags: debug_info

    - include: tasks/packages_redhat.yaml
      when: ansible_distribution == 'Rocky Linux' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora' or ansible_os_family == 'RedHat'
      
    - include: tasks/packages_debian.yaml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      
    - include: tasks/packages_generic.yaml
    - include: tasks/mounts.yaml
    - include: tasks/dconf.yaml
    - include: tasks/vim.yaml
    - include: tasks/sudoers.yaml
    - include: tasks/keys.yaml
