---
- hosts: localhost
  become: false

  vars_files:
    - files/packages.yaml
    - files/mounts.yaml
    - files/dconf.yaml

  tasks:
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
      tags: debug_info

    - import_tasks: tasks/packages_redhat.yaml
      when: ansible_system == 'Linux' and (ansible_distribution == 'Rocky Linux' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora' or ansible_os_family == 'RedHat')
      tags:
        - desktop
      
    - import_tasks: tasks/packages_debian.yaml
      when: ansible_system == 'Linux' and (ansible_distribution == 'Debian' or ansible_distribution == 'Devuan' or ansible_distribution == 'Ubuntu')
      tags:
        - desktop

    - import_tasks: tasks/packages_mac.yaml
      when: ansible_system == 'Darwin'
      tags:
        - desktop

    - import_tasks: tasks/folders.yaml
      when: ansible_system == 'Linux'
      tags:
        - desktop     

    - import_tasks: tasks/packages_generic.yaml
      when: ansible_system == 'Linux'
      tags:
        - desktop
    - import_tasks: tasks/mounts.yaml
      when: ansible_system == 'Linux'
      tags:
        - desktop
    - import_tasks: tasks/dconf.yaml
      when: ansible_system == 'Linux'
      tags:
        - desktop
    - import_tasks: tasks/bash.yaml
      tags:
        - desktop
        - headless
    - import_tasks: tasks/fonts.yaml
      when: ansible_system == 'Linux'
      tags:
        - desktop
    - import_tasks: tasks/sudoers.yaml
      when: ansible_system == 'Linux'
      tags:
        - desktop
    - import_tasks: tasks/keys.yaml
      when: ansible_system == 'Linux'
      tags:
        - desktop

  roles:
    - ansible-role-jet-brains-toolbox

- name: Setup vim
  hosts: localhost
  tags: vim
  roles:
    - vim
