---
- hosts: localhost
  become: false

  vars_files:
    - files/packages.yaml
    - files/mounts.yaml
    - files/dconf.yaml
    - files/vim.yaml

  roles:
    - ansible-role-jet-brains-toolbox

  tasks:
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
      tags: debug_info

    - include: tasks/packages_redhat.yaml
      when: ansible_distribution == 'Rocky Linux' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora' or ansible_os_family == 'RedHat'
      tags: ['desktop']
      
    - include: tasks/packages_debian.yaml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      tags: ['desktop']
      
    - include: tasks/packages_generic.yaml tags=desktop
    - include: tasks/mounts.yaml tags=desktop
    - include: tasks/dconf.yaml tags=desktop
    - include: tasks/vim.yaml tags=desktop,headless
    - include: tasks/bash.yaml tags=desktop,headless
    - include: tasks/fonts.yaml tags=desktop
    - include: tasks/sudoers.yaml tags=desktop
    - include: tasks/keys.yaml tags=desktop
