packloadall

set expandtab
set shiftwidth=4
set tabstop=4
set autoindent
set completeopt=longest,menuone

set backspace=indent,eol,start

" Enter key selects autocomplete item
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

set number

set termguicolors
syntax on

map q <Nop>
set mouse=a

let perldll=system('ldd /usr/bin/perl | grep -oE "\/.*(libperl.so[\.0-9]*)"')


perl << EOF
my $HOME = $ENV{HOME};
do "$HOME/.vim/VimExtensions.pm";
EOF

nnoremap cc :perl &comment_line <CR>
xnoremap cc :perl &comment_block <CR>

perl &set_theme;

filetype plugin on
filetype plugin indent on
let g:NERDCreateDefaultMappings = 1
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1

" Nerd Tree Config

" Open the nerd tree
nnoremap <C-t> :NERDTreeMirror<CR>:NERDTreeFocus<CR>
nnoremap ww :w <CR>
nnoremap wq :wq <CR>
nnoremap ws cs

" Exit Vim if NERDTree is the only window remaining in the only tab.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif


au User lsp_setup call lsp#register_server({
    \ 'name': 'pylsp',
    \ 'cmd': {server_info->['pylsp']},
    \ 'allowlist': ['python'],
    \ })

au User lsp_setup call lsp#register_server({
    \ 'name': 'pls',
    \ 'cmd': {server_info->['pls']},
    \ 'allowlist': ['perl'],
    \ })

autocmd User lsp_setup call lsp#register_server({
    \'name': 'texlab',
    \'cmd': {server_info->[expand('/path/to/texlab')]},
    \'whitelist': ['tex']
    \})

let g:ale_linters = {
    \   'python': ['pylsp'],
    \   'perl': ['pls'],
    \   'tex': ['texlab'],
    \ }

set completeopt=longest,menuone
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
