#!/bin/bash

FILE=/mnt/share/vault.img
MNTPT=/vault

function mount_vault() {
	pass="$(zenity --title="Enter Vault Password"  --password)"

	echo -e $pass | cryptsetup open --type luks $FILE vault -

	mount /dev/mapper/vault $MNTPT

	chown -R rhys:rhys $MNTPT

	echo "Mounted $FILE at $MNTPT"
}

function unmount_vault() {
	umount $MNTPT
	cryptsetup close vault
	echo "Unmounted $MNTPT"
}

if [ `id -u` -ne 0 ]
then
	sudo $0 $@
	exit 1
fi

if [ "$1" == "-u" ]
then
	unmount_vault
else
	mount_vault
fi
