execute pathogen#infect()

set expandtab
set shiftwidth=4
set tabstop=4
set autoindent

set backspace=indent,eol,start

set number

set termguicolors
colorscheme apprentice
syntax on

map q <Nop>
set mouse=a

let perldll=system('whereis libperl.so | sed "s/^.*: //g"')

perl << EOF
my $HOME = $ENV{HOME};
do "$HOME/.vim/VimExtensions.pm";
EOF

nnoremap cc :perl &comment_line <CR>
xnoremap cc :perl &comment_block <CR>

filetype plugin on
let g:NERDCreateDefaultMappings = 1
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1
