- name: Ensure .fonts exists
  file:
    path: "{{ home_dir }}/.fonts"
    state: directory
    recurse: no
    mode: 0750

- name: Download Fonts (zip)
  unarchive:
    src: "{{ item.path }}"
    dest: "{{ home_dir }}/.fonts/"
    remote_src: yes
  loop:
    - name: PlexMono
      path: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/IBMPlexMono.zip

- name: Get gnome-terminal profile
  shell: sh files/terminal-profile.sh
  register: terminal_profile
