- name: Ensure .fonts exists
  file:
    path: "{{ home_dir }}/.fonts"
    state: directory
    recurse: no
    mode: 0750

- name: Unzip Fonts
  unarchive:
    src: "{{ item.path }}"
    dest: "{{ home_dir }}/.fonts/"
    copy: no
  loop:
    - name: BigBlue
      path: files/BigBlueTerminal.zip

- name: Download fonts
  git:
    dest: "{{ home_dir }}/.fonts/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: yes
    update: yes
    recursive: no
  loop:
  - name: sfpro
    url: https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts

- name: Get gnome-terminal profile
  shell: sh files/terminal-profile.sh
  register: terminal_profile

- name: Set gnome-terminal font
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  loop:
    - key: "/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile.stdout }}/use-system-font"
      value: "false"
    - key: "/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile.stdout }}/font"
      value: "'BigBlueTermPlus Nerd Font Mono 12'"
