- name: Ensure .fonts exists
  file:
    path: "{{ home_dir }}/.fonts"
    state: directory
    recurse: no
    mode: 0750

- name: Unzip Fonts
  unarchive:
    src: "{{ item.path }}"
    dest: "{{ home_dir }}/.fonts/"
    copy: no
  loop:
    - name: BigBlue
      path: files/BigBlueTerminal.zip
    - name: JetBrainsMono
      path: files/JetBrainsMono.zip

- name: Download fonts
  git:
    dest: "{{ home_dir }}/.fonts/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: yes
    update: yes
    recursive: no
  loop:
  - name: sfpro
    url: https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts

- name: Get gnome-terminal profile
  shell: sh files/terminal-profile.sh
  register: terminal_profile

- name: Set gnome-terminal font
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  loop:
    - key: "/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile.stdout }}/use-system-font"
      value: "false"
    - key: "/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile.stdout }}/font"
      value: "'JetBrains Mono Nerd Font Mono 12'"
    - key: "/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile.stdout }}/palette"
      value: "['rgb(7,54,66)', 'rgb(220,50,47)', 'rgb(133,153,0)', 'rgb(181,137,0)', 'rgb(38,139,210)', 'rgb(211,54,130)', 'rgb(42,161,152)', 'rgb(238,232,213)', 'rgb(0,43,54)', 'rgb(203,75,22)', 'rgb(88,110,117)', 'rgb(101,123,131)', 'rgb(131,148,150)', 'rgb(108,113,196)', 'rgb(147,161,161)', 'rgb(253,246,227)']"
