- name: Copy .ssh directory
  become_user: rhys
  copy:
    src: "{{ mountpoint }}/keys/.ssh"
    dest: "{{ home_dir }}"
    
- name: Change private key permissions
  become_user: rhys
  file:
    path: "{{ item }}"
    state: file
    mode: "0600"
  with_items:
    - "{{ home_dir }}/.ssh/id_rsa"
    - "{{ home_dir }}/.ssh/warwick_rsa"
