- name: Copy .ssh directory
  copy:
    src: "{{ mntshare_mountpoint }}/keys/.ssh"
    dest: "{{ home_dir }}"
  when: mntshare_stat == 0 # When mntshare is mounted
    
- name: Change private key permissions
  file:
    path: "{{ item }}"
    state: file
    mode: "0600"
  with_items:
    - "{{ home_dir }}/.ssh/id_rsa"
    - "{{ home_dir }}/.ssh/warwick_rsa"
  when: mntshare_stat == 0 # When mntshare is mounted
