- name: Check auto.master
  copy: src=auto.master, dest=/etc/auto.master

- name: Check auto.nfs
  copy: src=auto.nfs, dest=/etc/auto.nfs

- name: Enable autofs
  service:
    name: autofs
    state: started
    enabled: yes
