- name: check mountpoint exist
  become: true
  ansible.builtin.file:
    path: "{{ mntshare_mountpoint }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: mount network share
  become: true
  ansible.posix.mount:
    src: "{{ mntshare_path }}"
    path: "{{ mntshare_mountpoint }}"
    fstype: nfs
    opts: "{{ mntshare_shareopts }}"
    state: mounted
