- name: Update Repositories
  become: true
  apt: update_cache=yes
  changed_when: False

- name: Upgrade Packages
  become: true
  apt: upgrade=dist force_apt_get=yes
 
- name: Add Podman GPG Key
  become: true
  when: ansible_distribution_version == '20.04'
  apt_key:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_20.04/Release.key
    state: present
    
- name: Add Podman Repository
  become: true
  when: ansible_distribution_version == '20.04'
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04 /
    state: present

- name: Install Debian Native Packages
  become: true
  apt:
    name: "{{ packages_debian }}"
    state: latest
