- name: Install General Native Packages
  become: true
  package:
    name: "{{ packages_general }}"
    state: latest

- name: Add Flathub Remote
  become: true
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Update Flatpaks
  become: true
  shell:
    cmd: flatpak update --noninteractive

- name: Install Flatpak Packages
  become: true
  flatpak:
    name: "{{ item }}"
    method: system
    state: present
  loop: "{{ flatpaks }}"


- name: Install Distrobox
  become: true
  shell: |
    curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh

- name: Install User Binaries
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: '0755'
    owner: rhys
  loop: "{{ binaries }}"

- name: Get Zips
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.name }}"
    mode: '0777'
    owner: rhys
  loop: "{{ zips }}"

- name: Unzip Zips
  unarchive:
    src: "/tmp/{{ item.name }}"
    dest: "{{ item.dest }}"
    include: "{{ item.files }}"
    mode: '0777'
    owner: rhys
  loop: "{{ zips }}"


- name: Install cpan packages
  cpanm:
    name: "{{ item }}"
    notest: True
  loop: "{{ cpan }}"

- name: Install pip packages
  pip:
    name: "{{ item }}"
    extra_args: --user
  loop: "{{ pip }}"

- name: Install golang packages
  ansible.builtin.command: "go install {{ item }}"
  loop: "{{ golang }}"
