- name: Copy .vim directory
  become_user: rhys
  copy:
    src: .vim
    dest: "{{ home_dir }}"

- name: Ensure .vim/{autoload,bundle} directory exists
  become_user: rhys
  file:
    path: "{{ item }}"
    state: directory
    recurse: no
    mode: 0750
  loop:
    - "{{ vim_dir }}/autoload"
    - "{{ vim_dir }}/bundle"
    
- name: Ensure Pathogen is in place
  become_user: rhys
  get_url:
    dest: "{{ vim_dir }}/autoload/pathogen.vim"
    url: https://tpo.pe/pathogen.vim

- name: Deploy plugins
  become_user: rhys
  git:
    dest: "{{ vim_dir }}/bundle/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: yes
    update: yes
    recursive: no
  loop:
  - name: vim-airline
    url: https://github.com/vim-airline/vim-airline
  - name: apprentice # Apprentice theme
    url: https://github.com/romainl/Apprentice
