execute pathogen#infect()

set expandtab
set shiftwidth=4
set tabstop=4
set autoindent
set completeopt=longest,menuone
set colorcolumn=80

set backspace=indent,eol,start

set number

set termguicolors
syntax on

map q <Nop>
set mouse=a

nnoremap cc :call nerdcommenter#Comment(0,"toggle")<C-m>
xnoremap cc :call nerdcommenter#Comment(0,"toggle")<C-m>

colorscheme gruvbox

filetype plugin on
filetype plugin indent on

let g:NERDCreateDefaultMappings = 0
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1
let g:NERDTreeDirArrowExpandable = '+'
let g:NERDTreeDirArrowCollapsible = '-'

" Nerd Tree Config

" Open the nerd tree
nnoremap <C-t> :NERDTreeMirror<CR>:NERDTreeFocus<CR>
nnoremap ww :w <CR>
nnoremap wq :wq <CR>
nnoremap ws cs

" Exit Vim if NERDTree is the only window remaining in the only tab.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 &&
    \ exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif


au User lsp_setup call lsp#register_server({
    \ 'name': 'pylsp',
    \ 'cmd': {server_info->['pylsp']},
    \ 'allowlist': ['python'],
    \ })

au User lsp_setup call lsp#register_server({
    \ 'name': 'pls',
    \ 'cmd': {server_info->['pls']},
    \ 'allowlist': ['perl'],
    \ })

autocmd User lsp_setup call lsp#register_server({
    \'name': 'texlab',
    \'cmd': {server_info->[expand('/path/to/texlab')]},
    \'whitelist': ['tex']
    \})

let g:ale_linters = {
    \   'python': ['pylsp'],
    \   'perl': ['pls'],
    \   'tex': ['texlab'],
    \ }
